EntitySchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - fieldData
    - fieldDatumIds
    - isTemplate
    - name
    - parentGroup
    - parentGroupId
    - tags
    - tagIds
    - template
    - templateId
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    fieldData:
      items:
        oneOf:
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_BoolEntity"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_DateEntity"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_IntEntity"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_StringEntity"
      type: array
    fieldDatumIds:
      items:
        type: integer
      type: array
    isTemplate:
      type: boolean
    name:
      type: string
    parentGroup:
      $ref: "../../openapi.root.yml#/components/schemas/Group"
      readOnly: true
    parentGroupId:
      nullable: true
      type: integer
    tags:
      items:
        $ref: "../../openapi.root.yml#/components/schemas/Tag"
      readOnly: true
      type: array
    tagIds:
      items:
        type: integer
      type: array
    template:
      $ref: "../../openapi.root.yml#/components/schemas/EntityTemplate"
      readOnly: true
    templateId:
      type: integer
    transactorType:
      type: integer

EntityTemplateSchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - fields
    - fieldIds
    - isTemplate
    - name
    - parentGroup
    - parentGroupId
    - tags
    - tagIds
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    fields:
      items:
        $ref: "../../openapi.root.yml#/components/schemas/Field"
      readOnly: true
      type: array
    fieldIds:
      items:
        type: integer
      type: array
    fieldData:
      items:
        oneOf:
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_BoolEntity"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_DateEntity"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_IntEntity"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_StringEntity"
      type: array
    fieldDatumIds:
      items:
        type: integer
      type: array
    isTemplate:
      type: boolean
    name:
      type: string
    parentGroup:
      $ref: "../../openapi.root.yml#/components/schemas/Group"
      readOnly: true
    parentGroupId:
      nullable: true
      type: integer
    tags:
      items:
        $ref: "../../openapi.root.yml#/components/schemas/Tag"
      readOnly: true
      type: array
    tagIds:
      items:
        type: integer
      type: array
    transactorType:
      type: integer

NullableEntitySchema:
  nullable: true
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - fieldData
    - fieldDatumIds
    - isTemplate
    - name
    - parentGroup
    - parentGroupId
    - tags
    - tagIds
    - template
    - templateId
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    fieldData:
      items:
        oneOf:
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_BoolEntity"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_DateEntity"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_IntEntity"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_StringEntity"
      type: array
    fieldDatumIds:
      items:
        type: integer
      type: array
    isTemplate:
      type: boolean
    name:
      type: string
    parentGroup:
      $ref: "../../openapi.root.yml#/components/schemas/Group"
      readOnly: true
    parentGroupId:
      nullable: true
      type: integer
    tags:
      items:
        $ref: "../../openapi.root.yml#/components/schemas/Tag"
      readOnly: true
      type: array
    tagIds:
      items:
        type: integer
      type: array
    template:
      $ref: "../../openapi.root.yml#/components/schemas/EntityTemplate"
      readOnly: true
    templateId:
      type: integer
    transactorType:
      type: integer
