FieldSchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - childFieldComponents
    - childFieldComponentIds
    - fieldType
    - fieldTypeId
    - isComponentOnly
    - name
    - parentFieldComponentId
    - tags
    - tagIds
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    childFieldComponents:
      items:
        $ref: "../../openapi.root.yml#/components/schemas/FieldComponent"
      type: array
    childFieldComponentIds:
      items:
        type: integer
      type: array
    fieldType:
      readOnly: true
      $ref: "../../openapi.root.yml#/components/schemas/FieldType"
    fieldTypeId:
      type: integer
    isComponentOnly:
      type: boolean
    name:
      type: string
    parentFieldComponent:
      $ref: "../../openapi.root.yml#/components/schemas/FieldComponent"
    parentFieldComponentId:
      nullable: true
      type: integer
    tags:
      items:
        $ref: "../../openapi.root.yml#/components/schemas/Tag"
      readOnly: true
      type: array
    tagIds:
      items:
        type: integer
      type: array
