FieldTypeSchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - fieldTypeComponents
    - fieldTypeComponentIds
    - name
    - tags
    - tagIds
    - type
    - validator
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    fieldTypeComponents:
      items:
        type: object
        properties:
          $ref: "../../openapi.root.yml#/components/schemas/FieldType"
      readOnly: true
      type: array
    fieldTypeComponentIds:
      items:
        type: integer
      type: array
    name:
      type: string
    tags:
      items:
        type: object
        properties:
          $ref: "../../openapi.root.yml#/components/schemas/Tag"
      readOnly: true
      type: array
    tagIds:
      items:
        type: integer
      type: array
    type:
      enum:
        - Text
        - Number
        - Date
        - Boolean
        - null
      nullable: true
      type: string
    validator:
      nullable: true
      type: string
