FieldSchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - isComponentOnly
    - fieldType
    - fieldTypeId
    - name
    - tags
    - tagIds
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    isComponentOnly:
      type: boolean
    fieldType:
      readOnly: true
      type: object
      additionalProperties:
        $ref: "../../openapi.root.yml#/components/schemas/FieldType"
    fieldTypeId:
      type: integer
    name:
      type: string
    tags:
      items:
        type: object
        additionalProperties:
          $ref: "../../openapi.root.yml#/components/schemas/Tag"
      readOnly: true
      type: array
    tagIds:
      items:
        type: integer
      type: array
