BoolAccount_RequestSchema:
  type: object
  properties:
    fieldId:
      type: integer
    boolValue:
      type: boolean
    accountId:
      type: integer
BoolEntity_RequestSchema:
  type: object
  properties:
    fieldId:
      type: integer
    boolValue:
      type: boolean
    entityId:
      type: integer
BoolTransaction_RequestSchema:
  type: object
  properties:
    fieldId:
      type: integer
    boolValue:
      type: boolean
    transactionId:
      type: integer
DateAccount_RequestSchema:
  type: object
  properties:
    FieldId:
      type: integer
    dateValue:
      type: string
      format: date-time
    accountId:
      type: integer
DateEntity_RequestSchema:
  type: object
  properties:
    fieldId:
      type: integer
    dateValue:
      type: string
      format: date-time
    entityId:
      type: integer
DateTransaction_RequestSchema:
  type: object
  properties:
    fieldId:
      type: integer
    dateValue:
      type: string
      format: date-time
    transactionId:
      type: integer
IntAccount_RequestSchema:
  type: object
  properties:
    fieldId:
      type: integer
    intValue:
      type: integer
    accountId:
      type: integer
IntEntity_RequestSchema:
  type: object
  properties:
    fieldId:
      type: integer
    intValue:
      type: integer
    entityId:
      type: integer
IntTransaction_RequestSchema:
  type: object
  properties:
    fieldId:
      type: integer
    intValue:
      type: integer
    transactionId:
      type: integer
StringAccount_RequestSchema:
  type: object
  properties:
    fieldId:
      type: integer
    stringValue:
      type: string
    accountId:
      type: integer
StringEntity_RequestSchema:
  type: object
  properties:
    fieldId:
      type: integer
    stringValue:
      type: string
    entityId:
      type: integer
StringTransaction_RequestSchema:
  type: object
  properties:
    fieldId:
      type: integer
    stringValue:
      type: string
    transactionId:
      type: integer

RequestBody:
  required: true
  content:
    application/json:
      schema:
        oneOf:
          - $ref: "#/BoolAccount_RequestSchema"
          - $ref: "#/BoolEntity_RequestSchema"
          - $ref: "#/BoolTransaction_RequestSchema"
          - $ref: "#/DateAccount_RequestSchema"
          - $ref: "#/DateEntity_RequestSchema"
          - $ref: "#/DateTransaction_RequestSchema"
          - $ref: "#/IntAccount_RequestSchema"
          - $ref: "#/IntEntity_RequestSchema"
          - $ref: "#/IntTransaction_RequestSchema"
          - $ref: "#/StringAccount_RequestSchema"
          - $ref: "#/StringEntity_RequestSchema"
          - $ref: "#/StringTransaction_RequestSchema"

BoolAccount_ResponseSchema:
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    fieldId:
      type: integer
    boolValue:
      type: boolean
    accountId:
      type: integer
BoolEntity_ResponseSchema:
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    fieldId:
      type: integer
    boolValue:
      type: boolean
    entityId:
      type: integer
BoolTransaction_ResponseSchema:
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    fieldId:
      type: integer
    boolValue:
      type: boolean
    transactionId:
      type: integer
DateAccount_ResponseSchema:
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    fieldId:
      type: integer
    dateValue:
      type: string
      format: date-time
    accountId:
      type: integer
DateEntity_ResponseSchema:
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    fieldId:
      type: integer
    dateValue:
      type: string
      format: date-time
    entityId:
      type: integer
DateTransaction_ResponseSchema:
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    fieldId:
      type: integer
    dateValue:
      type: string
      format: date-time
    transactionId:
      type: integer
IntAccount_ResponseSchema:
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    fieldId:
      type: integer
    intValue:
      type: integer
    accountId:
      type: integer
IntEntity_ResponseSchema:
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    fieldId:
      type: integer
    intValue:
      type: integer
    entityId:
      type: integer
IntTransaction_ResponseSchema:
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    fieldId:
      type: integer
    intValue:
      type: integer
    transactionId:
      type: integer
StringAccount_ResponseSchema:
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    fieldId:
      type: integer
    stringValue:
      type: string
    accountId:
      type: integer
StringEntity_ResponseSchema:
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    fieldId:
      type: integer
    stringValue:
      type: string
    entityId:
      type: integer
StringTransaction_ResponseSchema:
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    fieldId:
      type: integer
    stringValue:
      type: string
    transactionId:
      type: integer
