BoolAccount_FieldDatumSchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - field
    - fieldId
    - boolValue
    - accountId
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    field:
      $ref: "../../openapi.root.yml#/components/schemas/Field"
      readOnly: true
    fieldId:
      type: integer
    boolValue:
      type: boolean
    accountId:
      nullable: true
      type: integer
BoolEntity_FieldDatumSchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - field
    - fieldId
    - boolValue
    - entityId
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    field:
      $ref: "../../openapi.root.yml#/components/schemas/Field"
      readOnly: true
    fieldId:
      type: integer
    boolValue:
      type: boolean
    entityId:
      nullable: true
      type: integer
BoolTransaction_FieldDatumSchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - field
    - fieldId
    - boolValue
    - transactionId
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    field:
      $ref: "../../openapi.root.yml#/components/schemas/Field"
      readOnly: true
    fieldId:
      type: integer
    boolValue:
      type: boolean
    transactionId:
      nullable: true
      type: integer

DateAccount_FieldDatumSchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - field
    - fieldId
    - dateValue
    - accountId
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    field:
      $ref: "../../openapi.root.yml#/components/schemas/Field"
      readOnly: true
    fieldId:
      type: integer
    dateValue:
      format: date-time
      type: string
    accountId:
      nullable: true
      type: integer
DateEntity_FieldDatumSchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - field
    - fieldId
    - dateValue
    - entityId
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    field:
      $ref: "../../openapi.root.yml#/components/schemas/Field"
      readOnly: true
    fieldId:
      type: integer
    dateValue:
      format: date-time
      type: string
    entityId:
      nullable: true
      type: integer
DateTransaction_FieldDatumSchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - field
    - fieldId
    - dateValue
    - transactionId
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    field:
      $ref: "../../openapi.root.yml#/components/schemas/Field"
      readOnly: true
    fieldId:
      type: integer
    dateValue:
      format: date-time
      type: string
    transactionId:
      nullable: true
      type: integer

IntAccount_FieldDatumSchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - field
    - fieldId
    - intValue
    - accountId
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    field:
      $ref: "../../openapi.root.yml#/components/schemas/Field"
      readOnly: true
    fieldId:
      type: integer
    intValue:
      type: integer
    accountId:
      nullable: true
      type: integer
IntEntity_FieldDatumSchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - field
    - fieldId
    - intValue
    - entityId
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    field:
      $ref: "../../openapi.root.yml#/components/schemas/Field"
      readOnly: true
    fieldId:
      type: integer
    intValue:
      type: integer
    entityId:
      nullable: true
      type: integer
IntTransaction_FieldDatumSchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - field
    - fieldId
    - intValue
    - transactionId
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    field:
      $ref: "../../openapi.root.yml#/components/schemas/Field"
      readOnly: true
    fieldId:
      type: integer
    intValue:
      type: integer
    transactionId:
      nullable: true
      type: integer

StringAccount_FieldDatumSchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - field
    - fieldId
    - stringValue
    - accountId
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    field:
      $ref: "../../openapi.root.yml#/components/schemas/Field"
      readOnly: true
    fieldId:
      type: integer
    stringValue:
      type: string
    accountId:
      nullable: true
      type: integer
StringEntity_FieldDatumSchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - field
    - fieldId
    - stringValue
    - entityId
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    field:
      $ref: "../../openapi.root.yml#/components/schemas/Field"
      readOnly: true
    fieldId:
      type: integer
    stringValue:
      type: string
    entityId:
      nullable: true
      type: integer
StringTransaction_FieldDatumSchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - field
    - fieldId
    - stringValue
    - transactionId
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    field:
      $ref: "../../openapi.root.yml#/components/schemas/Field"
      readOnly: true
    fieldId:
      type: integer
    stringValue:
      type: string
    transactionId:
      nullable: true
      type: integer

RequestBody:
  required: true
  content:
    application/json:
      schema:
        oneOf:
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_BoolAccount"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_BoolEntity"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_BoolTransaction"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_DateAccount"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_DateEntity"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_DateTransaction"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_IntAccount"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_IntEntity"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_IntTransaction"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_StringAccount"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_StringEntity"
          - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_StringTransaction"
