TagSchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - name
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      readOnly: true
      type: string
      format: date-time
    updatedAt:
      readOnly: true
      type: string
      format: date-time
    name:
      type: string
    accountIds:
      readOnly: true
      type: array
      items:
        type: integer
    entityIds:
      readOnly: true
      type: array
      items:
        type: integer
    transactionIds:
      readOnly: true
      type: array
      items:
        type: integer
