UserSchema:
  type: object
  required:
    - id
    - createdAt
    - updatedAt
    - email
    - password
    - roles
    - roleIds
    - username
  properties:
    id:
      readOnly: true
      type: integer
    createdAt:
      format: date-time
      readOnly: true
      type: string
    updatedAt:
      format: date-time
      readOnly: true
      type: string
    email:
      type: string
    password:
      writeOnly: true
      type: string
    roles:
      items:
        $ref: "../../openapi.root.yml#/components/schemas/Role"
      readOnly: true
      type: array
    roleIds:
      items:
        type: integer
      type: array
    username:
      type: string
