RequestSchema:
  type: object
  properties:
    username:
      type: string
    email:
      type: string
    password:
      type: string
      format: password
    RoleIds:
      type: array
      items:
        type: integer
ResponseSchema:
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    username:
      type: string
    email:
      type: string
    roleIds:
      type: array
      items:
        type: integer
