# fly.toml app configuration file generated for ff-server on 2023-06-05T23:01:43-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ff-server"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
