openapi: 3.0.0
servers:
  - url: 'https://flexible-finance-server.herokuapp.com/api'
    description: Production server
  - url: 'http://localhost:5000/api'
    description: Local server
info:
  description: This is the server for Flexible Finance.
  version: 1.0.0
  title: OpenAPI Flexible Finance
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /auth/signup:
    post:
      responses:
        '200':
          description: OK
components:
  schemas:
    Role:
      type: object
      properties:
        id:
          type: integer
        createdAt:
          type: string
        updatedAt:
          type: string
        name:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
        createdAt:
          type: string
        updatedAt:
          type: string
        username:
          type: string
        email:
          type: string
        password:
          type: string
          format: password

