type: object
properties:
  id:
    type: integer
  createdAt:
    type: string
    format: date-time
  updatedAt:
    type: string
    format: date-time
  name:
    type: string
  fields:
    type: array
    items:
      $ref: ../../openapi.root.yml#/components/schemas/Field
  accountGroup:
    $ref: ../../openapi.root.yml#/components/schemas/AccountGroup
  data:
    type: array
    items:
      $ref: ../../openapi.root.yml#/components/schemas/FieldDatum
  tags:
    type: array
    items:
      $ref: ../../openapi.root.yml#/components/schemas/Tag
  template:
    $ref: ../../openapi.root.yml#/components/schemas/Template
