type: object
properties:
  name:
    type: string
  FieldIds:
    type: array
    items:
      type: integer
  AccountGroupId:
    type: integer
  DatumIds:
    type: array
    items:
      type: integer
  TagIds:
    type: array
    items:
      type: integer
  TemplateId:
    type: integer
