type: object
properties:
  id:
    type: integer
  createdAt:
    type: string
    format: date-time
  updatedAt:
    type: string
    format: date-time
  name:
    type: string
  DatumIds:
    type: array
    items:
      type: integer
  TagIds:
    type: array
    items:
      type: integer
  TemplateId:
    type: integer
