type: object
properties:
  id:
    type: integer
  createdAt:
    type: string
    format: date-time
  updatedAt:
    type: string
    format: date-time
  fieldId:
    type: integer
  stringValue:
    type: string
  intValue:
    type: integer
  dateValue:
    type: string
    format: date-time
  boolValue:
    type: boolean
  accountId:
    type: integer
  entityId:
    type: integer
  transactionId:
    type: integer
