type: object
properties:
  id:
    type: integer
  createdAt:
    type: string
    format: date-time
  updatedAt:
    type: string
    format: date-time
  stringValue:
    type: string
  intValue:
    type: integer
  dateValue:
    type: string
    format: date-time
  boolValue:
    type: boolean
  account:
    $ref: ../../openapi.root.yml#/components/schemas/Account
  field:
    $ref: ../../openapi.root.yml#/components/schemas/Field
  entity:
    $ref: ../../openapi.root.yml#/components/schemas/Entity
  transaction:
    $ref: ../../openapi.root.yml#/components/schemas/Transaction
