type: object
properties:
  id:
    type: integer
  createdAt:
    type: string
    format: date-time
  updatedAt:
    type: string
    format: date-time
  name:
    type: string
  data:
    type: array
    items:
      $ref: ./openapi.part.yml#/FieldDatum
  fieldType:
    $ref: ./openapi.part.yml#/FieldType
  template:
    $ref: ./openapi.part.yml#/Template
