type: object
properties:
  id:
    type: integer
  createdAt:
    type: string
    format: date-time
  updatedAt:
    type: string
    format: date-time
  name:
    type: string
  data:
    type: array
    items:
      $ref: ../../openapi.root.yml#/components/schemas/FieldDatum
  fieldType:
    $ref: ../../openapi.root.yml#/components/schemas/FieldType
  template:
    $ref: ../../openapi.root.yml#/components/schemas/Template
