RequestSchema:
  type: object
  properties:
    name:
      type: string
    FieldTypeId:
      type: integer
    isComponentOnly:
      type: boolean
ResponseSchema:
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    name:
      type: string
    FieldDatumIds:
      type: array
      items:
        type: integer
    FieldTypeId:
      type: integer
    AccountIds:
      type: array
      items:
        type: integer
    EntityIds:
      type: array
      items:
        type: integer
    TransactionIds:
      type: array
      items:
        type: integer
    isComponentOnly:
      type: boolean
