import Account from "./Account";
import AccountGroup from "./AccountGroup";
import Entity from "./Entity";
import EntityTag from "./EntityTag";
import Field from "./Field";
import FieldDatum from "./FieldDatum";
import FieldType from "./FieldType";
import Report from "./Report";
import ReportTag from "./ReportTag";
import Role from "./Role";
import Status from "./Status";
import Tag from "./Tag";
import Template from "./Template";
import TemplateField from "./TemplateField";
import TemplateTag from "./TemplateTag";
import Transaction from "./Transaction";
import TransactionFile from "./TransactionFile";
import TransactionTag from "./TransactionTag";
import Type from "./Type";
import User from "./User";
import UserRole from "./UserRole";

export * from "./Account";
export * from "./AccountGroup";
export * from "./AccountTag";
export * from "./Entity";
export * from "./EntityTag";
export * from "./Field";
export * from "./FieldDatum";
export * from "./FieldType";
export * from "./File";
export * from "./Report";
export * from "./ReportTag";
export * from "./Role";
export * from "./Status";
export * from "./Tag";
export * from "./Template";
export * from "./TemplateField";
export * from "./TemplateTag";
export * from "./Transaction";
export * from "./TransactionFile";
export * from "./TransactionTag";
export * from "./Type";
export * from "./User";
export * from "./UserRole";

export function syncAllModels(): void {
  void Account.sync();
  void AccountGroup.sync();
  void Entity.sync();
  void EntityTag.sync();
  void Field.sync();
  void FieldDatum.sync();
  void FieldType.sync();
  void Report.sync();
  void ReportTag.sync();
  void Role.sync();
  void Status.sync();
  void Tag.sync();
  void Template.sync();
  void TemplateField.sync();
  void TemplateTag.sync();
  void Transaction.sync();
  void TransactionFile.sync();
  void TransactionTag.sync();
  void Type.sync();
  void User.sync();
  void UserRole.sync();
}
