Role:
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
    updatedAt:
      type: string
    name:
      type: string
User:
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
    updatedAt:
      type: string
    username:
      type: string
    email:
      type: string
    password:
      type: string
      format: password
