Account:
  $ref: ./account.openapi.yml
AccountGroup:
  $ref: ./accountGroup.openapi.yml
Entity:
  $ref: ./entity.openapi.yml
Field:
  $ref: ./field.openapi.yml
FieldDatum:
  $ref: ./fieldDatum.openapi.yml
FieldType:
  $ref: ./fieldType.openapi.yml
File:
  $ref: ./file.openapi.yml
Report:
  $ref: ./report.openapi.yml
Role:
  $ref: ./role.openapi.yml
Status:
  $ref: ./status.openapi.yml
Tag:
  $ref: ./tag.openapi.yml
Template:
  $ref: ./template.openapi.yml
Transaction:
  $ref: ./transaction.openapi.yml
Type:
  $ref: ./type.openapi.yml
User:
  $ref: ./user.openapi.yml
