type: object
properties:
  id:
    type: integer
  createdAt:
    type: string
    format: date-time
  updatedAt:
    type: string
    format: date-time
  name:
    type: string
  accounts:
    type: array
    items:
      $ref: ../../openapi.root.yml#/components/schemas/Account
  entities:
    type: array
    items:
      $ref: ../../openapi.root.yml#/components/schemas/Entity
  reports:
    type: array
    items:
      $ref: ../../openapi.root.yml#/components/schemas/Report
  templates:
    type: array
    items:
      $ref: ../../openapi.root.yml#/components/schemas/Template
  transactions:
    type: array
    items:
      $ref: ../../openapi.root.yml#/components/schemas/Transaction
