RequestSchema:
  type: object
  properties:
    name:
      type: string
    type:
      type: string
      enum:
        - Account
        - Entity
        - Transaction
    FieldIds:
      type: array
      items:
        type: integer
    TagIds:
      type: array
      items:
        type: integer
ResponseSchema:
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    name:
      type: string
    type:
      type: string
      enum:
        - Account
        - Entity
        - Transaction
    AccountIds:
      type: array
      items:
        type: integer
    EntityIds:
      type: array
      items:
        type: integer
    TransactionIds:
      type: array
      items:
        type: integer
    FieldIds:
      type: array
      items:
        type: integer
    TagIds:
      type: array
      items:
        type: integer
    Fields:
      type: array
      items:
        $ref: ../../openapi.root.yml#/components/schemas/Field_ResponseSchema
    Tags:
      type: array
      items:
        $ref: ../../openapi.root.yml#/components/schemas/Tag_ResponseSchema
