type: object
properties:
  id:
    type: integer
  createdAt:
    type: string
    format: date-time
  updatedAt:
    type: string
    format: date-time
  name:
    type: string
  type:
    type: string
    enum:
      - Account
      - Entity
      - Transaction
  AccountIds:
    type: array
    items:
      type: integer
  FieldIds:
    type: array
    items:
      type: integer
  TagIds:
    type: array
    items:
      type: integer
