RequestSchema:
  type: object
  properties:
    name:
      type: string
    FieldDatumIds:
      type: array
      items:
        type: integer
    FieldIds:
      type: array
      items:
        type: integer
    fieldValues:
      type: object
    TagIds:
      type: array
      items:
        type: integer
    TemplateId:
      type: integer
    isTemplate:
      type: boolean
    SourceTransactorId:
      type: integer
    RecipientTransactorId:
      type: integer
ResponseSchema:
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    name:
      type: string
    FieldDatumIds:
      type: array
      items:
        type: integer
    FieldIds:
      type: array
      items:
        type: integer
    TagIds:
      type: array
      items:
        type: integer
    TemplateId:
      type: integer
      nullable: true
    SourceTransactorId:
      type: integer
    RecipientTransactorId:
      type: integer
