type: object
properties:
  id:
    type: integer
  createdAt:
    type: string
    format: date-time
  updatedAt:
    type: string
    format: date-time
  name:
    type: string
  data:
    type: array
    items:
      $ref: ../../openapi.root.yml#/components/schemas/FieldDatum
  files:
    type: array
    items:
      $ref: ../../openapi.root.yml#/components/schemas/File
  tags:
    type: array
    items:
      $ref: ../../openapi.root.yml#/components/schemas/Tag
