AccountRequests:
AccountIdRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/idParameter"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Account"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/idParameter"
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/Account_RequestSchema"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Account"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
AccountsRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/offsetParameter"
      - $ref: "../../openapi.root.yml#/components/parameters/limitParameter"
      - $ref: "../../openapi.root.yml#/components/parameters/nameParameter"
      - $ref: "../../openapi.root.yml#/components/parameters/fieldIdsParameter"
      - $ref: "../../openapi.root.yml#/components/parameters/fieldDatumIdsParameter"
      - $ref: "../../openapi.root.yml#/components/parameters/groupIdsParameter"
      - $ref: "../../openapi.root.yml#/components/parameters/tagIdsParameter"
      - $ref: "../../openapi.root.yml#/components/parameters/templateIdsParameter"
      - $ref: "../../openapi.root.yml#/components/parameters/isTemplateParameter"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Accounts"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  post:
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/Account_RequestSchema"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Account"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
AccountResponse:
  description: Returns the account's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          account:
            $ref: "../../openapi.root.yml#/components/schemas/Account_ResponseSchema"
AccountsResponse:
  description: Returns the accounts' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          accounts:
            type: array
            nullable: true
            items:
              $ref: "../../openapi.root.yml#/components/schemas/Account_ResponseSchema"
          templates:
            type: array
            nullable: true
            items:
              $ref: "../../openapi.root.yml#/components/schemas/Account_ResponseSchema"
