AccountRequests:
  get:
    parameters:
      - name: x-access-token
        in: header
        required: true
        schema:
          type: string
      - name: accountId
        in: path
        required: true
        schema:
          type: integer
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Account"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  post:
    parameters:
      - name: x-access-token
        in: header
        required: true
        schema:
          type: string
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/Account"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Account"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - name: x-access-token
        in: header
        required: true
        schema:
          type: string
      - name: accountId
        in: path
        required: true
        schema:
          type: integer
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/Account"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Account"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
AccountsRequests:
  get:
    parameters:
      - name: x-access-token
        in: header
        required: true
        schema:
          type: string
      - name: offset
        in: query
        schema:
          type: integer
      - name: limit
        in: query
        schema:
          type: integer
      - name: name
        in: query
        schema:
          type: string
      - name: accountGroupIds
        in: query
        schema:
          type: array
          items:
            type: number
      - name: tagIds
        in: query
        schema:
          type: array
          items:
            type: number
      - name: templateIds
        in: query
        schema:
          type: array
          items:
            type: number
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Accounts"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
AccountResponse:
  description: Returns the account's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          account:
            $ref: "../../openapi.root.yml#/components/schemas/Account"
AccountsResponse:
  description: Returns the accounts' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          accounts:
            type: array
            items:
              $ref: "../../openapi.root.yml#/components/schemas/Account"
