AccountGroupRequests:
  get:
    parameters:
      - name: x-access-token
        in: header
        required: true
        schema:
          type: string
      - name: accountGroupId
        in: path
        required: true
        schema:
          type: integer
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/AccountGroup"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  post:
    parameters:
      - name: x-access-token
        in: header
        required: true
        schema:
          type: string
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/AccountGroup"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/AccountGroup"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - name: x-access-token
        in: header
        required: true
        schema:
          type: string
      - name: accountGroupId
        in: path
        required: true
        schema:
          type: integer
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/AccountGroup"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/AccountGroup"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
AccountGroupsRequests:
  get:
    parameters:
      - name: x-access-token
        in: header
        required: true
        schema:
          type: string
      - name: offset
        in: query
        schema:
          type: integer
      - name: limit
        in: query
        schema:
          type: integer
      - name: name
        in: query
        schema:
          type: string
      - name: accountIds
        in: query
        schema:
          type: array
          items:
            type: number
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/AccountGroups"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
AccountGroupResponse:
  description: Returns the account group's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          accountGroup:
            $ref: "../../openapi.root.yml#/components/schemas/AccountGroup"
AccountGroupsResponse:
  description: Returns the account groups' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          accountGroups:
            type: array
            items:
              $ref: "../../openapi.root.yml#/components/schemas/AccountGroup"
