TestAll:
  get:
    security: []
    responses:
      200:
        description: Returns sample content.
        content:
          text/plain:
            schema:
              type: string
TestUser:
  get:
    responses:
      200:
        description: Returns sample content.
        content:
          text/plain:
            schema:
              type: string
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
TestAdmin:
  get:
    responses:
      200:
        description: Returns sample content.
        content:
          text/plain:
            schema:
              type: string
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
