SignUp:
  post:
    security: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                type: string
              email:
                type: string
              password:
                type: string
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
SignIn:
  post:
    security: []
    requestBody:
      description: Optional description in *Markdown*
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
    responses:
      200:
        description: Returns the user's info and an access token.
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                username:
                  type: string
                email:
                  type: string
                roles:
                  type: array
                  items:
                    type: string
                    enum:
                      - ROLE_ADMIN
                      - ROLE_USER
                accessToken:
                  type: string
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      404:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
