EntityIdRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/path_id"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Entity"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/path_id"
    requestBody:
      $ref: "../../openapi.root.yml#/components/requestBodies/Entity"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Entity"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
EntitiesRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/query_offset"
      - $ref: "../../openapi.root.yml#/components/parameters/query_limit"
      - $ref: "../../openapi.root.yml#/components/parameters/query_name"
      - $ref: "../../openapi.root.yml#/components/parameters/query_fieldIds"
      - $ref: "../../openapi.root.yml#/components/parameters/query_fieldDatumIds"
      - $ref: "../../openapi.root.yml#/components/parameters/query_groupIds"
      - $ref: "../../openapi.root.yml#/components/parameters/query_tagIds"
      - $ref: "../../openapi.root.yml#/components/parameters/query_templateIds"
      - $ref: "../../openapi.root.yml#/components/parameters/query_isTemplate"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Entities"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  post:
    requestBody:
      $ref: "../../openapi.root.yml#/components/requestBodies/Entity"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Entity"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
EntityResponse:
  description: Returns the entity's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          entity:
            $ref: "../../openapi.root.yml#/components/schemas/Entity_Response"
EntitiesResponse:
  description: Returns the entities' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          entities:
            type: array
            nullable: true
            items:
              $ref: "../../openapi.root.yml#/components/schemas/Entity_Response"
          templates:
            type: array
            nullable: true
            items:
              $ref: "../../openapi.root.yml#/components/schemas/Entity_Response"
