EntityRequests:
  get:
    parameters:
      - name: x-access-token
        in: header
        required: true
        schema:
          type: string
      - name: entityId
        in: path
        required: true
        schema:
          type: integer
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Entity"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  post:
    parameters:
      - name: x-access-token
        in: header
        required: true
        schema:
          type: string
      - name: entityId
        in: path
        required: true
        schema:
          type: integer
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/Entity"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Entity"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - name: x-access-token
        in: header
        required: true
        schema:
          type: string
      - name: entityId
        in: path
        required: true
        schema:
          type: integer
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/Entity"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Entity"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
EntitiesRequests:
  get:
    parameters:
      - name: x-access-token
        in: header
        required: true
        schema:
          type: string
      - name: offset
        in: query
        schema:
          type: integer
      - name: limit
        in: query
        schema:
          type: integer
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Entities"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
EntityResponse:
  description: Returns the entity's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          entity:
            $ref: "../../openapi.root.yml#/components/schemas/Entity"
EntitiesResponse:
  description: Returns the entities' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          entities:
            type: array
            items:
              $ref: "../../openapi.root.yml#/components/schemas/Entity"
