FieldDatumIdRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/id"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/FieldDatum"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/id"
    requestBody:
      $ref: "../../openapi.root.yml#/components/requestBodies/FieldDatum"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/FieldDatum"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
FieldDataRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/offset"
      - $ref: "../../openapi.root.yml#/components/parameters/limit"
      - $ref: "../../openapi.root.yml#/components/parameters/name"
      - $ref: "../../openapi.root.yml#/components/parameters/fieldIds"
      - $ref: "../../openapi.root.yml#/components/parameters/accountIds"
      - $ref: "../../openapi.root.yml#/components/parameters/entityIds"
      - $ref: "../../openapi.root.yml#/components/parameters/transactionIds"
      - name: stringValue
        in: query
        schema:
          type: string
      - name: intValueGT
        in: query
        schema:
          type: number
      - name: intValueLT
        in: query
        schema:
          type: number
      - name: dateValue
        in: query
        schema:
          type: string
      - name: boolValue
        in: query
        schema:
          type: boolean
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/FieldData"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  post:
    requestBody:
      $ref: "../../openapi.root.yml#/components/requestBodies/FieldDatum"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/FieldDatum"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
FieldDatumResponse:
  description: Returns the field datum's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          fieldDatum:
            oneOf:
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_BoolAccount_Response"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_BoolEntity_Response"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_BoolTransaction_Response"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_DateAccount_Response"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_DateEntity_Response"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_DateTransaction_Response"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_IntAccount_Response"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_IntEntity_Response"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_IntTransaction_Response"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_StringAccount_Response"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_StringEntity_Response"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_StringTransaction_Response"
FieldDataResponse:
  description: Returns the field data's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          fieldData:
            type: array
            items:
              oneOf:
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_BoolAccount_Response"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_BoolEntity_Response"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_BoolTransaction_Response"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_DateAccount_Response"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_DateEntity_Response"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_DateTransaction_Response"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_IntAccount_Response"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_IntEntity_Response"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_IntTransaction_Response"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_StringAccount_Response"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_StringEntity_Response"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_StringTransaction_Response"
