FieldTypeIdRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/path_id"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/FieldType"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/path_id"
    requestBody:
      $ref: "../../openapi.root.yml#/components/requestBodies/FieldType"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/FieldType"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
FieldTypesRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/query_offset"
      - $ref: "../../openapi.root.yml#/components/parameters/query_limit"
      - $ref: "../../openapi.root.yml#/components/parameters/query_name"
      - $ref: "../../openapi.root.yml#/components/parameters/query_fieldIds"
      - $ref: "../../openapi.root.yml#/components/parameters/query_tagIds"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/FieldTypes"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  post:
    requestBody:
      $ref: "../../openapi.root.yml#/components/requestBodies/Field"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/FieldType"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
FieldTypeResponse:
  description: Returns the field type's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          fieldType:
            $ref: "../../openapi.root.yml#/components/schemas/FieldType_Response"
FieldTypesResponse:
  description: Returns the field types' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          fieldTypes:
            type: array
            items:
              $ref: "../../openapi.root.yml#/components/schemas/FieldType_Response"
