FieldDatumIdRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/path_id"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/FieldDatum"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/path_id"
    requestBody:
      $ref: "../../openapi.root.yml#/components/requestBodies/FieldDatum"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/FieldDatum"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
FieldDataRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/query_offset"
      - $ref: "../../openapi.root.yml#/components/parameters/query_limit"
      - $ref: "../../openapi.root.yml#/components/parameters/query_name"
      - $ref: "../../openapi.root.yml#/components/parameters/query_fieldIds"
      - $ref: "../../openapi.root.yml#/components/parameters/query_accountIds"
      - $ref: "../../openapi.root.yml#/components/parameters/query_entityIds"
      - $ref: "../../openapi.root.yml#/components/parameters/query_transactionIds"
      - name: stringValue
        in: query
        schema:
          type: string
      - name: intValueGT
        in: query
        schema:
          type: number
      - name: intValueLT
        in: query
        schema:
          type: number
      - name: dateValue
        in: query
        schema:
          type: string
      - name: boolValue
        in: query
        schema:
          type: boolean
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/FieldData"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  post:
    requestBody:
      $ref: "../../openapi.root.yml#/components/requestBodies/FieldDatum"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/FieldDatum"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
FieldDatumResponse:
  description: Returns the field datum's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          fieldDatum:
            oneOf:
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_BoolAccount"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_BoolEntity"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_BoolTransaction"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_DateAccount"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_DateEntity"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_DateTransaction"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_IntAccount"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_IntEntity"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_IntTransaction"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_StringAccount"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_StringEntity"
              - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_StringTransaction"
FieldDataResponse:
  description: Returns the field data's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          fieldData:
            type: array
            items:
              oneOf:
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_BoolAccount"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_BoolEntity"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_BoolTransaction"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_DateAccount"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_DateEntity"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_DateTransaction"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_IntAccount"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_IntEntity"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_IntTransaction"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_StringAccount"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_StringEntity"
                - $ref: "../../openapi.root.yml#/components/schemas/FieldDatum_StringTransaction"
