GroupIdRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/id"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Group"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/id"
    requestBody:
      $ref: "../../openapi.root.yml#/components/requestBodies/Group"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Group"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
GroupsRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/offset"
      - $ref: "../../openapi.root.yml#/components/parameters/limit"
      - $ref: "../../openapi.root.yml#/components/parameters/name"
      - $ref: "../../openapi.root.yml#/components/parameters/accountIds"
      - $ref: "../../openapi.root.yml#/components/parameters/entityIds"
      - $ref: "../../openapi.root.yml#/components/parameters/groupIds"
      - $ref: "../../openapi.root.yml#/components/parameters/tagIds"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Groups"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  post:
    requestBody:
      $ref: "../../openapi.root.yml#/components/requestBodies/Group"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Group"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
GroupResponse:
  description: Returns the group's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          group:
            $ref: "../../openapi.root.yml#/components/schemas/Group_Response"
GroupsResponse:
  description: Returns the groups' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          groups:
            type: array
            items:
              $ref: "../../openapi.root.yml#/components/schemas/Group_Response"
