GroupRequests:
  post:
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/Group_RequestSchema"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Group"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
GroupIdRequests:
  get:
    parameters:
      - name: GroupId
        in: path
        required: true
        schema:
          type: integer
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Group"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - name: GroupId
        in: path
        required: true
        schema:
          type: integer
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/Group_RequestSchema"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Group"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
GroupsRequests:
  get:
    parameters:
      - name: offset
        in: query
        schema:
          type: integer
      - name: limit
        in: query
        schema:
          type: integer
      - name: name
        in: query
        schema:
          type: string
      - name: AccountIds
        in: query
        schema:
          type: array
          items:
            type: number
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Groups"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
GroupResponse:
  description: Returns the account group's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          group:
            $ref: "../../openapi.root.yml#/components/schemas/Group_ResponseSchema"
GroupsResponse:
  description: Returns the account groups' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          groups:
            type: array
            items:
              $ref: "../../openapi.root.yml#/components/schemas/Group_ResponseSchema"
