GroupRequests:
GroupIdRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/path_id"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Group"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/path_id"
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/Group"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Group"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
GroupsRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/query_name"
      - $ref: "../../openapi.root.yml#/components/parameters/query_offset"
      - $ref: "../../openapi.root.yml#/components/parameters/query_limit"
      - $ref: "../../openapi.root.yml#/components/parameters/query_tagIds"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Groups"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  post:
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/Group"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Group"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
GroupResponse:
  description: Returns the group's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          group:
            $ref: "../../openapi.root.yml#/components/schemas/Group"
GroupsResponse:
  description: Returns the groups' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          groups:
            type: array
            nullable: true
            items:
              $ref: "../../openapi.root.yml#/components/schemas/Group"
          templates:
            type: array
            nullable: true
            items:
              $ref: "../../openapi.root.yml#/components/schemas/Group"
