RoleIdRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/id"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Role"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/id"
    requestBody:
      $ref: "../../openapi.root.yml#/components/requestBodies/Role"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Role"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
RolesRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/offset"
      - $ref: "../../openapi.root.yml#/components/parameters/limit"
      - $ref: "../../openapi.root.yml#/components/parameters/name"
      - name: userIds
        in: query
        schema:
          type: array
          items:
            type: number
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Roles"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  post:
    requestBody:
      $ref: "../../openapi.root.yml#/components/requestBodies/Role"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Role"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
RoleResponse:
  description: Returns the role's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          role:
            $ref: "../../openapi.root.yml#/components/schemas/Role_Response"
RolesResponse:
  description: Returns the roles' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          roles:
            type: array
            items:
              $ref: "../../openapi.root.yml#/components/schemas/Role_Response"
