TagIdRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/path_id"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Tag"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/path_id"
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/Tag"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Tag"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
TagsRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/query_accountIds"
      - $ref: "../../openapi.root.yml#/components/parameters/query_entityIds"
      - $ref: "../../openapi.root.yml#/components/parameters/query_fieldIds"
      - $ref: "../../openapi.root.yml#/components/parameters/query_fieldTypeIds"
      - $ref: "../../openapi.root.yml#/components/parameters/query_groupIds"
      - $ref: "../../openapi.root.yml#/components/parameters/query_limit"
      - $ref: "../../openapi.root.yml#/components/parameters/query_offset"
      - $ref: "../../openapi.root.yml#/components/parameters/query_name"
      - $ref: "../../openapi.root.yml#/components/parameters/query_transactionIds"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Tags"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  post:
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/Tag"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Tag"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
TagResponse:
  description: Returns the tag's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          tag:
            $ref: "../../openapi.root.yml#/components/schemas/Tag"
TagsResponse:
  description: Returns the tags' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          tags:
            type: array
            items:
              $ref: "../../openapi.root.yml#/components/schemas/Tag"
