TagRequests:
  post:
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/Tag"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Tag"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
TagIdRequests:
  get:
    parameters:
      - name: TagId
        in: path
        required: true
        schema:
          type: integer
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Tag"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - name: TagId
        in: path
        required: true
        schema:
          type: integer
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/Tag"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Tag"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
TagsRequests:
  get:
    parameters:
      - name: offset
        in: query
        schema:
          type: integer
      - name: limit
        in: query
        schema:
          type: integer
      - name: name
        in: query
        schema:
          type: string
      - name: AccountIds
        in: query
        schema:
          type: array
          items:
            type: number
      - name: EntityIds
        in: query
        schema:
          type: array
          items:
            type: number
      - name: reportIds
        in: query
        schema:
          type: array
          items:
            type: number
      - name: TemplateIds
        in: query
        schema:
          type: array
          items:
            type: number
      - name: TransactionIds
        in: query
        schema:
          type: array
          items:
            type: number
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Tags"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
TagResponse:
  description: Returns the tag's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          tag:
            $ref: "../../openapi.root.yml#/components/schemas/Tag"
TagsResponse:
  description: Returns the tags' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          tags:
            type: array
            items:
              $ref: "../../openapi.root.yml#/components/schemas/Tag"
