TemplateRequests:
  post:
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/Template"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Template"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
TemplateIdRequests:
  get:
    parameters:
      - name: TemplateId
        in: path
        required: true
        schema:
          type: integer
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Template"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - name: TemplateId
        in: path
        required: true
        schema:
          type: integer
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/Template"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Template"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
TemplatesRequests:
  get:
    parameters:
      - name: offset
        in: query
        schema:
          type: integer
      - name: limit
        in: query
        schema:
          type: integer
      - name: name
        in: query
        schema:
          type: string
      - name: type
        in: query
        schema:
          type: string
          enum:
            - Account
            - Entity
            - Transaction
      - name: AccountIds
        in: query
        schema:
          type: array
          items:
            type: number
      - name: FieldIds
        in: query
        schema:
          type: array
          items:
            type: number
      - name: TagIds
        in: query
        schema:
          type: array
          items:
            type: number
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Templates"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
TemplateResponse:
  description: Returns the template's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          template:
            $ref: "../../openapi.root.yml#/components/schemas/Template"
TemplatesResponse:
  description: Returns the templates' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          templates:
            type: array
            items:
              $ref: "../../openapi.root.yml#/components/schemas/Template"
