TransactionRequests:
  post:
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/Transaction"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Transaction"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
TransactionIdRequests:
  get:
    parameters:
      - name: transactionId
        in: path
        required: true
        schema:
          type: integer
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Transaction"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - name: transactionId
        in: path
        required: true
        schema:
          type: integer
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/Transaction"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Transaction"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
TransactionsRequests:
  get:
    parameters:
      - name: offset
        in: query
        schema:
          type: integer
      - name: limit
        in: query
        schema:
          type: integer
      - name: name
        in: query
        schema:
          type: string
      - name: datumIds
        in: query
        schema:
          type: array
          items:
            type: number
      - name: fileIds
        in: query
        schema:
          type: array
          items:
            type: number
      - name: tagIds
        in: query
        schema:
          type: array
          items:
            type: number
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Transactions"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
TransactionResponse:
  description: Returns the transaction's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          transaction:
            $ref: "../../openapi.root.yml#/components/schemas/Transaction"
TransactionsResponse:
  description: Returns the transactions' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          transactions:
            type: array
            items:
              $ref: "../../openapi.root.yml#/components/schemas/Transaction"
