TransactionIdRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/path_id"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Transaction"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/path_id"
    requestBody:
      $ref: "../../openapi.root.yml#/components/requestBodies/Transaction"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Transaction"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
TransactionsRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/query_offset"
      - $ref: "../../openapi.root.yml#/components/parameters/query_limit"
      - $ref: "../../openapi.root.yml#/components/parameters/query_fieldIds"
      - $ref: "../../openapi.root.yml#/components/parameters/query_fieldDatumIds"
      - $ref: "../../openapi.root.yml#/components/parameters/query_tagIds"
      - $ref: "../../openapi.root.yml#/components/parameters/query_templateIds"
      - $ref: "../../openapi.root.yml#/components/parameters/query_isTemplate"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Transactions"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  post:
    requestBody:
      $ref: "../../openapi.root.yml#/components/requestBodies/Transaction"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Transaction"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
TransactionResponse:
  description: Returns the transaction's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          transaction:
            $ref: "../../openapi.root.yml#/components/schemas/Transaction_Response"
TransactionsResponse:
  description: Returns the transactions' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          transactions:
            type: array
            nullable: true
            items:
              $ref: "../../openapi.root.yml#/components/schemas/Transaction_Response"
          templates:
            type: array
            nullable: true
            items:
              $ref: "../../openapi.root.yml#/components/schemas/Transaction_Response"
