TransactorIdRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/id"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Transactor"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/id"
    requestBody:
      $ref: "../../openapi.root.yml#/components/requestBodies/Transactor"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Transactor"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
TransactorsRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/offset"
      - $ref: "../../openapi.root.yml#/components/parameters/limit"
      - $ref: "../../openapi.root.yml#/components/parameters/name"
      - $ref: "../../openapi.root.yml#/components/parameters/fieldIds"
      - $ref: "../../openapi.root.yml#/components/parameters/fieldDatumIds"
      - $ref: "../../openapi.root.yml#/components/parameters/groupIds"
      - $ref: "../../openapi.root.yml#/components/parameters/tagIds"
      - $ref: "../../openapi.root.yml#/components/parameters/templateIds"
      - $ref: "../../openapi.root.yml#/components/parameters/isTemplate"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Transactors"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  post:
    requestBody:
      $ref: "../../openapi.root.yml#/components/requestBodies/Transactor"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Transactor"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
TransactorResponse:
  description: Returns the transactor's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          transactor:
            $ref: "../../openapi.root.yml#/components/schemas/Transactor_Response"
TransactorsResponse:
  description: Returns the transactors' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          transactors:
            type: array
            items:
              $ref: "../../openapi.root.yml#/components/schemas/Transactor_Response"
