UserRequests:
UserIdRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/path_id"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/User"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/path_id"
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/User"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/User"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
UsersRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/query_name"
      - $ref: "../../openapi.root.yml#/components/parameters/query_offset"
      - $ref: "../../openapi.root.yml#/components/parameters/query_limit"
      - $ref: "../../openapi.root.yml#/components/parameters/query_roleIds"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Users"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  post:
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/User"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/User"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
UserResponse:
  description: Returns the user's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          user:
            $ref: "../../openapi.root.yml#/components/schemas/User"
UsersResponse:
  description: Returns the users' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          users:
            type: array
            nullable: true
            items:
              $ref: "../../openapi.root.yml#/components/schemas/User"
          templates:
            type: array
            nullable: true
            items:
              $ref: "../../openapi.root.yml#/components/schemas/User"
