UserIdRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/id"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/User"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/id"
    requestBody:
      $ref: "../../openapi.root.yml#/components/requestBodies/User"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/User"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
UsersRequests:
  get:
    parameters:
      - $ref: "../../openapi.root.yml#/components/parameters/offset"
      - $ref: "../../openapi.root.yml#/components/parameters/limit"
      - name: username
        in: query
        schema:
          type: string
      - name: email
        in: query
        schema:
          type: string
      - name: roleIds
        in: query
        schema:
          type: array
          items:
            type: number
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Users"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  post:
    requestBody:
      $ref: "../../openapi.root.yml#/components/requestBodies/User"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/User"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
UserResponse:
  description: Returns the user's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          user:
            $ref: "../../openapi.root.yml#/components/schemas/User_Response"
UsersResponse:
  description: Returns the users' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          users:
            type: array
            items:
              $ref: "../../openapi.root.yml#/components/schemas/User_Response"
