UserIdRequests:
  get:
    parameters:
      - name: UserId
        in: path
        required: true
        schema:
          type: integer
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/User"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  put:
    parameters:
      - name: UserId
        in: path
        required: true
        schema:
          type: integer
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/User_RequestSchema"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/User"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
UsersRequests:
  get:
    parameters:
      - name: offset
        in: query
        schema:
          type: integer
      - name: limit
        in: query
        schema:
          type: integer
      - name: name
        in: query
        schema:
          type: string
      - name: email
        in: query
        schema:
          type: string
      - name: RoleIds
        in: query
        schema:
          type: array
          items:
            type: number
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/Users"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
  post:
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi.root.yml#/components/schemas/User_RequestSchema"
    responses:
      200:
        $ref: "../../openapi.root.yml#/components/responses/User"
      400:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      401:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      403:
        $ref: "../../openapi.root.yml#/components/responses/Message"
      500:
        $ref: "../../openapi.root.yml#/components/responses/Message"
UserResponse:
  description: Returns the user's info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          user:
            $ref: "../../openapi.root.yml#/components/schemas/User_ResponseSchema"
UsersResponse:
  description: Returns the users' info.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          users:
            type: array
            items:
              $ref: "../../openapi.root.yml#/components/schemas/User_ResponseSchema"
