openapi: 3.0.0
servers:
  - url: https://flexible-finance-server.herokuapp.com/api
    description: Production server
  - url: http://localhost:5000/api
    description: Local server
info:
  description: >-
    This is the server for Flexible Finance.
  version: 1.0.0
  title: OpenAPI Flexible Finance
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
#tags:
paths:
  # Account Requests
  /getAccount:
    $ref: ./app/routes/account.openapi.yml#/GetAccount
  /getAccounts:
    $ref: ./app/routes/account.openapi.yml#/GetAccounts
  /createAccount:
    $ref: ./app/routes/account.openapi.yml#/CreateAccount
  # Authentication Requests
  /auth/signup:
    $ref: ./app/routes/auth.openapi.yml#/SignUp
  /auth/signin:
    $ref: ./app/routes/auth.openapi.yml#/SignIn
  # Template Requests
  /getTemplates:
    $ref: ./app/routes/template.openapi.yml#/GetTemplates
  /createTemplate:
    $ref: ./app/routes/template.openapi.yml#/CreateTemplate
  # User Test Requests
  /test/all:
    $ref: ./app/routes/user.openapi.yml#/TestAll
  /test/user:
    $ref: ./app/routes/user.openapi.yml#/TestUser
  /test/admin:
    $ref: ./app/routes/user.openapi.yml#/TestAdmin
components:
  responses:
    Message:
      description: a simple response with just a message
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Message"
  schemas:
    Message:
      type: object
      properties:
        message:
          type: string
    Account:
      $ref: ./database/models/account.openapi.yml
    AccountGroup:
      $ref: ./database/models/accountGroup.openapi.yml
    Entity:
      $ref: ./database/models/entity.openapi.yml
    Field:
      $ref: ./database/models/field.openapi.yml
    FieldDatum:
      $ref: ./database/models/fieldDatum.openapi.yml
    FieldType:
      $ref: ./database/models/fieldType.openapi.yml
    File:
      $ref: ./database/models/file.openapi.yml
    Report:
      $ref: ./database/models/report.openapi.yml
    Role:
      $ref: ./database/models/role.openapi.yml
    Status:
      $ref: ./database/models/status.openapi.yml
    Tag:
      $ref: ./database/models/tag.openapi.yml
    Template:
      $ref: ./database/models/template.openapi.yml
    Transaction:
      $ref: ./database/models/transaction.openapi.yml
    Type:
      $ref: ./database/models/type.openapi.yml
    User:
      $ref: ./database/models/user.openapi.yml
#  parameters:

