openapi: 3.0.3
servers:
  - url: https://flexible-finance-server.herokuapp.com/v1
    description: Production server
  - url: http://localhost:5001/v1
    description: Local server
info:
  description: >-
    This is the server for Flexible Finance.
  version: 1.0.0
  title: OpenAPI Flexible Finance
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
#tags:
paths:
  /accounts:
    $ref: ./app/routes/account.openapi.yml#/AccountsRequests
  /accounts/{AccountId}:
    $ref: ./app/routes/account.openapi.yml#/AccountIdRequests
  /auth/signup:
    $ref: ./app/routes/auth.openapi.yml#/SignUp
  /auth/signin:
    $ref: ./app/routes/auth.openapi.yml#/SignIn
  /api-docs:
    get:
      security: []
      responses:
        200:
          description: Returns API documentation.
          content:
            text/html:
              schema:
                type: string
  /entities:
    $ref: ./app/routes/entity.openapi.yml#/EntitiesRequests
  /entities/{EntityId}:
    $ref: ./app/routes/entity.openapi.yml#/EntityIdRequests
  /fields:
    $ref: ./app/routes/field.openapi.yml#/FieldsRequests
  /fields/{FieldId}:
    $ref: ./app/routes/field.openapi.yml#/FieldIdRequests
  /fieldData:
    $ref: ./app/routes/fieldDatum.openapi.yml#/FieldDataRequests
  /fieldData/{FieldDatumId}:
    $ref: ./app/routes/fieldDatum.openapi.yml#/FieldDatumIdRequests
  /fieldTypes:
    $ref: ./app/routes/fieldType.openapi.yml#/FieldTypesRequests
  /fieldTypes/{FieldTypeId}:
    $ref: ./app/routes/fieldType.openapi.yml#/FieldTypeIdRequests
  /groups:
    $ref: ./app/routes/group.openapi.yml#/GroupsRequests
  /groups/{GroupId}:
    $ref: ./app/routes/group.openapi.yml#/GroupIdRequests
  /roles:
    $ref: ./app/routes/role.openapi.yml#/RolesRequests
  /roles/{RoleId}:
    $ref: ./app/routes/role.openapi.yml#/RoleIdRequests
  /statuses:
    $ref: ./app/routes/status.openapi.yml#/StatusesRequests
  /statuses/{StatusId}:
    $ref: ./app/routes/status.openapi.yml#/StatusIdRequests
  /tags:
    $ref: ./app/routes/tag.openapi.yml#/TagsRequests
  /tags/{TagId}:
    $ref: ./app/routes/tag.openapi.yml#/TagIdRequests
  /test/all:
    $ref: ./app/routes/authTest.openapi.yml#/TestAll
  /test/user:
    $ref: ./app/routes/authTest.openapi.yml#/TestUser
  /test/admin:
    $ref: ./app/routes/authTest.openapi.yml#/TestAdmin
  /transactions:
    $ref: ./app/routes/transaction.openapi.yml#/TransactionsRequests
  /transactions/{TransactionId}:
    $ref: ./app/routes/transaction.openapi.yml#/TransactionIdRequests
  /transactors:
    $ref: ./app/routes/transactor.openapi.yml#/TransactorsRequests
  /transactors/{TransactorId}:
    $ref: ./app/routes/transactor.openapi.yml#/TransactorIdRequests
  /types:
    $ref: ./app/routes/type.openapi.yml#/TypesRequests
  /types/{TypeId}:
    $ref: ./app/routes/type.openapi.yml#/TypeIdRequests
  /users:
    $ref: ./app/routes/user.openapi.yml#/UsersRequests
  /users/{UserId}:
    $ref: ./app/routes/user.openapi.yml#/UserIdRequests
components:
  responses:
    Message:
      description: a simple response with just a message
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Message"
    Account:
      $ref: ./app/routes/account.openapi.yml#/AccountResponse
    Accounts:
      $ref: ./app/routes/account.openapi.yml#/AccountsResponse
    Entity:
      $ref: ./app/routes/entity.openapi.yml#/EntityResponse
    Entities:
      $ref: ./app/routes/entity.openapi.yml#/EntitiesResponse
    Field:
      $ref: ./app/routes/field.openapi.yml#/FieldResponse
    Fields:
      $ref: ./app/routes/field.openapi.yml#/FieldsResponse
    FieldDatum:
      $ref: ./app/routes/fieldDatum.openapi.yml#/FieldDatumResponse
    FieldData:
      $ref: ./app/routes/fieldDatum.openapi.yml#/FieldDataResponse
    FieldType:
      $ref: ./app/routes/fieldType.openapi.yml#/FieldTypeResponse
    FieldTypes:
      $ref: ./app/routes/fieldType.openapi.yml#/FieldTypesResponse
    Group:
      $ref: ./app/routes/group.openapi.yml#/GroupResponse
    Groups:
      $ref: ./app/routes/group.openapi.yml#/GroupsResponse
    Role:
      $ref: ./app/routes/role.openapi.yml#/RoleResponse
    Roles:
      $ref: ./app/routes/role.openapi.yml#/RolesResponse
    Status:
      $ref: ./app/routes/status.openapi.yml#/StatusResponse
    Statuses:
      $ref: ./app/routes/status.openapi.yml#/StatusesResponse
    Tag:
      $ref: ./app/routes/tag.openapi.yml#/TagResponse
    Tags:
      $ref: ./app/routes/tag.openapi.yml#/TagsResponse
    Transaction:
      $ref: ./app/routes/transaction.openapi.yml#/TransactionResponse
    Transactions:
      $ref: ./app/routes/transaction.openapi.yml#/TransactionsResponse
    Transactor:
      $ref: ./app/routes/transactor.openapi.yml#/TransactorResponse
    Transactors:
      $ref: ./app/routes/transactor.openapi.yml#/TransactorsResponse
    Type:
      $ref: ./app/routes/type.openapi.yml#/TypeResponse
    Types:
      $ref: ./app/routes/type.openapi.yml#/TypesResponse
    User:
      $ref: ./app/routes/user.openapi.yml#/UserResponse
    Users:
      $ref: ./app/routes/user.openapi.yml#/UsersResponse
  schemas:
    Message:
      type: object
      properties:
        message:
          type: string
    Account_RequestSchema:
      $ref: ./database/models/account.openapi.yml#/RequestSchema
    Account_ResponseSchema:
      $ref: ./database/models/account.openapi.yml#/ResponseSchema
    Entity_RequestSchema:
      $ref: ./database/models/entity.openapi.yml#/RequestSchema
    Entity_ResponseSchema:
      $ref: ./database/models/entity.openapi.yml#/ResponseSchema
    Field_RequestSchema:
      $ref: ./database/models/field.openapi.yml#/RequestSchema
    Field_ResponseSchema:
      $ref: ./database/models/field.openapi.yml#/ResponseSchema
    FieldDatum_BoolAccount_RequestSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/BoolAccount_RequestSchema
    FieldDatum_BoolEntity_RequestSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/BoolEntity_RequestSchema
    FieldDatum_BoolTransaction_RequestSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/BoolTransaction_RequestSchema
    FieldDatum_DateAccount_RequestSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/DateAccount_RequestSchema
    FieldDatum_DateEntity_RequestSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/DateEntity_RequestSchema
    FieldDatum_DateTransaction_RequestSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/DateTransaction_RequestSchema
    FieldDatum_IntAccount_RequestSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/IntAccount_RequestSchema
    FieldDatum_IntEntity_RequestSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/IntEntity_RequestSchema
    FieldDatum_IntTransaction_RequestSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/IntTransaction_RequestSchema
    FieldDatum_StringAccount_RequestSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/StringAccount_RequestSchema
    FieldDatum_StringEntity_RequestSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/StringEntity_RequestSchema
    FieldDatum_StringTransaction_RequestSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/StringTransaction_RequestSchema
    FieldDatum_BoolAccount_ResponseSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/BoolAccount_ResponseSchema
    FieldDatum_BoolEntity_ResponseSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/BoolEntity_ResponseSchema
    FieldDatum_BoolTransaction_ResponseSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/BoolTransaction_ResponseSchema
    FieldDatum_DateAccount_ResponseSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/DateAccount_ResponseSchema
    FieldDatum_DateEntity_ResponseSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/DateEntity_ResponseSchema
    FieldDatum_DateTransaction_ResponseSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/DateTransaction_ResponseSchema
    FieldDatum_IntAccount_ResponseSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/IntAccount_ResponseSchema
    FieldDatum_IntEntity_ResponseSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/IntEntity_ResponseSchema
    FieldDatum_IntTransaction_ResponseSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/IntTransaction_ResponseSchema
    FieldDatum_StringAccount_ResponseSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/StringAccount_ResponseSchema
    FieldDatum_StringEntity_ResponseSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/StringEntity_ResponseSchema
    FieldDatum_StringTransaction_ResponseSchema:
      $ref: ./database/models/fieldDatum.openapi.yml#/StringTransaction_ResponseSchema
    FieldType_RequestSchema:
      $ref: ./database/models/fieldType.openapi.yml#/RequestSchema
    FieldType_ResponseSchema:
      $ref: ./database/models/fieldType.openapi.yml#/ResponseSchema
    Group_RequestSchema:
      $ref: ./database/models/group.openapi.yml#/RequestSchema
    Group_ResponseSchema:
      $ref: ./database/models/group.openapi.yml#/ResponseSchema
    Role_RequestSchema:
      $ref: ./database/models/role.openapi.yml#/RequestSchema
    Role_ResponseSchema:
      $ref: ./database/models/role.openapi.yml#/ResponseSchema
    Status_RequestSchema:
      $ref: ./database/models/status.openapi.yml#/RequestSchema
    Status_ResponseSchema:
      $ref: ./database/models/status.openapi.yml#/ResponseSchema
    Tag_RequestSchema:
      $ref: ./database/models/tag.openapi.yml#/RequestSchema
    Tag_ResponseSchema:
      $ref: ./database/models/tag.openapi.yml#/ResponseSchema
    Transaction_RequestSchema:
      $ref: ./database/models/transaction.openapi.yml#/RequestSchema
    Transaction_ResponseSchema:
      $ref: ./database/models/transaction.openapi.yml#/ResponseSchema
    Transactor_RequestSchema:
      $ref: ./database/models/transactor.openapi.yml#/RequestSchema
    Transactor_ResponseSchema:
      $ref: ./database/models/transactor.openapi.yml#/ResponseSchema
    Type_RequestSchema:
      $ref: ./database/models/type.openapi.yml#/RequestSchema
    Type_ResponseSchema:
      $ref: ./database/models/type.openapi.yml#/ResponseSchema
    User_RequestSchema:
      $ref: ./database/models/user.openapi.yml#/RequestSchema
    User_ResponseSchema:
      $ref: ./database/models/user.openapi.yml#/ResponseSchema
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
#  parameters:
security:
  - bearerAuth: []
