openapi: 3.0.3
servers:
  - url: https://flexible-finance-server.herokuapp.com/v1
    description: Production server
  - url: http://localhost:5001/v1
    description: Local server
info:
  description: >-
    This is the server for Flexible Finance.
  version: 1.0.0
  title: OpenAPI Flexible Finance
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
#tags:
paths:
  /accounts:
    $ref: ./app/routes/account.openapi.yml#/AccountsRequests
  /accounts/{AccountId}:
    $ref: ./app/routes/account.openapi.yml#/AccountIdRequests
  /auth/signup:
    $ref: ./app/routes/auth.openapi.yml#/SignUp
  /auth/signin:
    $ref: ./app/routes/auth.openapi.yml#/SignIn
  /api-docs:
    get:
      security: []
      responses:
        200:
          description: Returns API documentation.
          content:
            text/html:
              schema:
                type: string
  /entities:
    $ref: ./app/routes/entity.openapi.yml#/EntitiesRequests
  /entities/{EntityId}:
    $ref: ./app/routes/entity.openapi.yml#/EntityIdRequests
  /fields:
    $ref: ./app/routes/field.openapi.yml#/FieldsRequests
  /fields/{FieldId}:
    $ref: ./app/routes/field.openapi.yml#/FieldIdRequests
  /fieldData:
    $ref: ./app/routes/fieldDatum.openapi.yml#/FieldDataRequests
  /fieldData/{FieldDatumId}:
    $ref: ./app/routes/fieldDatum.openapi.yml#/FieldDatumIdRequests
  /fieldTypes:
    $ref: ./app/routes/fieldType.openapi.yml#/FieldTypesRequests
  /fieldTypes/{FieldTypeId}:
    $ref: ./app/routes/fieldType.openapi.yml#/FieldTypeIdRequests
  /groups:
    $ref: ./app/routes/group.openapi.yml#/GroupsRequests
  /groups/{GroupId}:
    $ref: ./app/routes/group.openapi.yml#/GroupIdRequests
  /roles:
    $ref: ./app/routes/role.openapi.yml#/RolesRequests
  /roles/{RoleId}:
    $ref: ./app/routes/role.openapi.yml#/RoleIdRequests
  /tags:
    $ref: ./app/routes/tag.openapi.yml#/TagsRequests
  /tags/{TagId}:
    $ref: ./app/routes/tag.openapi.yml#/TagIdRequests
  /test/all:
    $ref: ./app/routes/authTest.openapi.yml#/TestAll
  /test/user:
    $ref: ./app/routes/authTest.openapi.yml#/TestUser
  /test/admin:
    $ref: ./app/routes/authTest.openapi.yml#/TestAdmin
  /transactions:
    $ref: ./app/routes/transaction.openapi.yml#/TransactionsRequests
  /transactions/{TransactionId}:
    $ref: ./app/routes/transaction.openapi.yml#/TransactionIdRequests
  /transactors:
    $ref: ./app/routes/transactor.openapi.yml#/TransactorsRequests
  /transactors/{TransactorId}:
    $ref: ./app/routes/transactor.openapi.yml#/TransactorIdRequests
  /users:
    $ref: ./app/routes/user.openapi.yml#/UsersRequests
  /users/{UserId}:
    $ref: ./app/routes/user.openapi.yml#/UserIdRequests
components:
  parameters:
    offset:
      name: offset
      in: query
      schema:
        type: integer
    limit:
      name: limit
      in: query
      schema:
        type: integer
    id:
      name: id
      in: path
      required: true
      schema:
        type: integer
    name:
      name: name
      in: query
      schema:
        type: string
    accountIds:
      name: accountIds
      in: query
      schema:
        type: array
        items:
          type: number
    entityIds:
      name: entityIds
      in: query
      schema:
        type: array
        items:
          type: number
    fieldIds:
      name: fieldIds
      in: query
      schema:
        type: array
        items:
          type: number
    fieldDatumIds:
      name: fieldDatumIds
      in: query
      schema:
        type: array
        items:
          type: number
    fieldTypeIds:
      name: fieldTypeIds
      in: query
      schema:
        type: array
        items:
          type: number
    groupIds:
      name: groupIds
      in: query
      schema:
        type: array
        items:
          type: number
    tagIds:
      name: tagIds
      in: query
      schema:
        type: array
        items:
          type: number
    templateIds:
      name: templateIds
      in: query
      schema:
        type: array
        items:
          type: number
    transactionIds:
      name: transactionIds
      in: query
      schema:
        type: array
        items:
          type: number
    isTemplate:
      name: isTemplate
      in: query
      schema:
        type: boolean
  requestBodies:
    Account:
      $ref: ./app/apiDtos/account.openapi.yml#/RequestBody
    Entity:
      $ref: ./app/apiDtos/entity.openapi.yml#/RequestBody
    Field:
      $ref: ./app/apiDtos/field.openapi.yml#/RequestBody
    FieldDatum:
      $ref: ./app/apiDtos/fieldDatum.openapi.yml#/RequestBody
    FieldType:
      $ref: ./app/apiDtos/fieldType.openapi.yml#/RequestBody
    Group:
      $ref: ./app/apiDtos/group.openapi.yml#/RequestBody
    Role:
      $ref: ./app/apiDtos/role.openapi.yml#/RequestBody
    Tag:
      $ref: ./app/apiDtos/tag.openapi.yml#/RequestBody
    Transaction:
      $ref: ./app/apiDtos/transaction.openapi.yml#/RequestBody
    Transactor:
      $ref: ./app/apiDtos/transactor.openapi.yml#/RequestBody
    User:
      $ref: ./app/apiDtos/user.openapi.yml#/RequestBody
  responses:
    Message:
      description: a simple response with just a message
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Message"
    Account:
      $ref: ./app/routes/account.openapi.yml#/AccountResponse
    Accounts:
      $ref: ./app/routes/account.openapi.yml#/AccountsResponse
    Entity:
      $ref: ./app/routes/entity.openapi.yml#/EntityResponse
    Entities:
      $ref: ./app/routes/entity.openapi.yml#/EntitiesResponse
    Field:
      $ref: ./app/routes/field.openapi.yml#/FieldResponse
    Fields:
      $ref: ./app/routes/field.openapi.yml#/FieldsResponse
    FieldDatum:
      $ref: ./app/routes/fieldDatum.openapi.yml#/FieldDatumResponse
    FieldData:
      $ref: ./app/routes/fieldDatum.openapi.yml#/FieldDataResponse
    FieldType:
      $ref: ./app/routes/fieldType.openapi.yml#/FieldTypeResponse
    FieldTypes:
      $ref: ./app/routes/fieldType.openapi.yml#/FieldTypesResponse
    Group:
      $ref: ./app/routes/group.openapi.yml#/GroupResponse
    Groups:
      $ref: ./app/routes/group.openapi.yml#/GroupsResponse
    Role:
      $ref: ./app/routes/role.openapi.yml#/RoleResponse
    Roles:
      $ref: ./app/routes/role.openapi.yml#/RolesResponse
    Tag:
      $ref: ./app/routes/tag.openapi.yml#/TagResponse
    Tags:
      $ref: ./app/routes/tag.openapi.yml#/TagsResponse
    Transaction:
      $ref: ./app/routes/transaction.openapi.yml#/TransactionResponse
    Transactions:
      $ref: ./app/routes/transaction.openapi.yml#/TransactionsResponse
    Transactor:
      $ref: ./app/routes/transactor.openapi.yml#/TransactorResponse
    Transactors:
      $ref: ./app/routes/transactor.openapi.yml#/TransactorsResponse
    User:
      $ref: ./app/routes/user.openapi.yml#/UserResponse
    Users:
      $ref: ./app/routes/user.openapi.yml#/UsersResponse
  schemas:
    Message:
      type: object
      properties:
        message:
          type: string
    Account_Response:
      $ref: ./app/apiDtos/account.openapi.yml#/ResponseSchema
    Entity_Response:
      $ref: ./app/apiDtos/entity.openapi.yml#/ResponseSchema
    Field_Response:
      $ref: ./app/apiDtos/field.openapi.yml#/ResponseSchema
    FieldDatum_BoolAccount_Response:
      $ref: ./app/apiDtos/fieldDatum.openapi.yml#/BoolAccount_ResponseSchema
    FieldDatum_BoolEntity_Response:
      $ref: ./app/apiDtos/fieldDatum.openapi.yml#/BoolEntity_ResponseSchema
    FieldDatum_BoolTransaction_Response:
      $ref: ./app/apiDtos/fieldDatum.openapi.yml#/BoolTransaction_ResponseSchema
    FieldDatum_DateAccount_Response:
      $ref: ./app/apiDtos/fieldDatum.openapi.yml#/DateAccount_ResponseSchema
    FieldDatum_DateEntity_Response:
      $ref: ./app/apiDtos/fieldDatum.openapi.yml#/DateEntity_ResponseSchema
    FieldDatum_DateTransaction_Response:
      $ref: ./app/apiDtos/fieldDatum.openapi.yml#/DateTransaction_ResponseSchema
    FieldDatum_IntAccount_Response:
      $ref: ./app/apiDtos/fieldDatum.openapi.yml#/IntAccount_ResponseSchema
    FieldDatum_IntEntity_Response:
      $ref: ./app/apiDtos/fieldDatum.openapi.yml#/IntEntity_ResponseSchema
    FieldDatum_IntTransaction_Response:
      $ref: ./app/apiDtos/fieldDatum.openapi.yml#/IntTransaction_ResponseSchema
    FieldDatum_StringAccount_Response:
      $ref: ./app/apiDtos/fieldDatum.openapi.yml#/StringAccount_ResponseSchema
    FieldDatum_StringEntity_Response:
      $ref: ./app/apiDtos/fieldDatum.openapi.yml#/StringEntity_ResponseSchema
    FieldDatum_StringTransaction_Response:
      $ref: ./app/apiDtos/fieldDatum.openapi.yml#/StringTransaction_ResponseSchema
    FieldType_Response:
      $ref: ./app/apiDtos/fieldType.openapi.yml#/ResponseSchema
    Group_Response:
      $ref: ./app/apiDtos/group.openapi.yml#/ResponseSchema
    Role_Response:
      $ref: ./app/apiDtos/role.openapi.yml#/ResponseSchema
    Tag_Response:
      $ref: ./app/apiDtos/tag.openapi.yml#/ResponseSchema
    Transaction_Response:
      $ref: ./app/apiDtos/transaction.openapi.yml#/ResponseSchema
    Transactor_Response:
      $ref: ./app/apiDtos/transactor.openapi.yml#/ResponseSchema
    User_Response:
      $ref: ./app/apiDtos/user.openapi.yml#/ResponseSchema
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
#  parameters:
security:
  - bearerAuth: []
