openapi: 3.0.0
servers:
  - url: https://flexible-finance-server.herokuapp.com/api-v1
    description: Production server
  - url: http://localhost:5000/api-v1
    description: Local server
info:
  description: >-
    This is the server for Flexible Finance.
  version: 1.0.0
  title: OpenAPI Flexible Finance
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
#tags:
paths:
  /account/{accountId}:
    $ref: ./app/routes/account.openapi.yml#/AccountRequests
  /accounts:
    $ref: ./app/routes/account.openapi.yml#/AccountsRequests
  /accountGroup/{accountGroupId}:
    $ref: ./app/routes/accountGroup.openapi.yml#/AccountGroupRequests
  /accountGroups:
    $ref: ./app/routes/accountGroup.openapi.yml#/AccountGroupsRequests
  /auth/signup:
    $ref: ./app/routes/auth.openapi.yml#/SignUp
  /auth/signin:
    $ref: ./app/routes/auth.openapi.yml#/SignIn
  /entity/{entityId}:
    $ref: ./app/routes/entity.openapi.yml#/EntityRequests
  /entities:
    $ref: ./app/routes/entity.openapi.yml#/EntitiesRequests
  /field/{fieldId}:
    $ref: ./app/routes/field.openapi.yml#/FieldRequests
  /fields:
    $ref: ./app/routes/field.openapi.yml#/FieldsRequests
  /fieldDatum/{fieldId}:
    $ref: ./app/routes/fieldDatum.openapi.yml#/FieldDatumRequests
  /fieldData:
    $ref: ./app/routes/fieldDatum.openapi.yml#/FieldDataRequests
  /fieldType/{fieldTypeId}:
    $ref: ./app/routes/fieldType.openapi.yml#/FieldTypeRequests
  /fieldTypes:
    $ref: ./app/routes/fieldType.openapi.yml#/FieldTypesRequests
  /role/{roleId}:
    $ref: ./app/routes/role.openapi.yml#/RoleRequests
  /roles:
    $ref: ./app/routes/role.openapi.yml#/RolesRequests
  /status/{statusId}:
    $ref: ./app/routes/status.openapi.yml#/StatusRequests
  /statuses:
    $ref: ./app/routes/status.openapi.yml#/StatusesRequests
  /tag/{tagId}:
    $ref: ./app/routes/tag.openapi.yml#/TagRequests
  /tags:
    $ref: ./app/routes/tag.openapi.yml#/TagsRequests
  /test/all:
    $ref: ./app/routes/user.openapi.yml#/TestAll
  /test/user:
    $ref: ./app/routes/user.openapi.yml#/TestUser
  /test/admin:
    $ref: ./app/routes/user.openapi.yml#/TestAdmin
  /template/{templateId}:
    $ref: ./app/routes/template.openapi.yml#/TemplateRequests
  /templates:
    $ref: ./app/routes/template.openapi.yml#/TemplatesRequests
  /transaction/{transactionId}:
    $ref: ./app/routes/transaction.openapi.yml#/TransactionRequests
  /transactions:
    $ref: ./app/routes/transaction.openapi.yml#/TransactionsRequests
components:
  responses:
    Message:
      description: a simple response with just a message
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Message"
    Account:
      $ref: ./app/routes/account.openapi.yml#/AccountResponse
    Accounts:
      $ref: ./app/routes/account.openapi.yml#/AccountsResponse
    AccountGroup:
      $ref: ./app/routes/accountGroup.openapi.yml#/AccountGroupResponse
    AccountGroups:
      $ref: ./app/routes/accountGroup.openapi.yml#/AccountGroupsResponse
    Entity:
      $ref: ./app/routes/entity.openapi.yml#/EntityResponse
    Entities:
      $ref: ./app/routes/entity.openapi.yml#/EntitiesResponse
    Field:
      $ref: ./app/routes/field.openapi.yml#/FieldResponse
    Fields:
      $ref: ./app/routes/field.openapi.yml#/FieldsResponse
    FieldDatum:
      $ref: ./app/routes/fieldDatum.openapi.yml#/FieldDatumResponse
    FieldData:
      $ref: ./app/routes/fieldDatum.openapi.yml#/FieldDataResponse
    FieldType:
      $ref: ./app/routes/fieldType.openapi.yml#/FieldTypeResponse
    FieldTypes:
      $ref: ./app/routes/fieldType.openapi.yml#/FieldTypesResponse
    Role:
      $ref: ./app/routes/role.openapi.yml#/RoleResponse
    Roles:
      $ref: ./app/routes/role.openapi.yml#/RolesResponse
    Status:
      $ref: ./app/routes/status.openapi.yml#/StatusResponse
    Statuses:
      $ref: ./app/routes/status.openapi.yml#/StatusesResponse
    Tag:
      $ref: ./app/routes/tag.openapi.yml#/TagResponse
    Tags:
      $ref: ./app/routes/tag.openapi.yml#/TagsResponse
    Template:
      $ref: ./app/routes/template.openapi.yml#/TemplateResponse
    Templates:
      $ref: ./app/routes/template.openapi.yml#/TemplatesResponse
    Transaction:
      $ref: ./app/routes/transaction.openapi.yml#/TransactionResponse
    Transactions:
      $ref: ./app/routes/transaction.openapi.yml#/TransactionsResponse
  schemas:
    Message:
      type: object
      properties:
        message:
          type: string
    Account:
      $ref: ./database/models/account.openapi.yml
    AccountGroup:
      $ref: ./database/models/accountGroup.openapi.yml
    Entity:
      $ref: ./database/models/entity.openapi.yml
    Field:
      $ref: ./database/models/field.openapi.yml
    FieldDatum:
      $ref: ./database/models/fieldDatum.openapi.yml
    FieldType:
      $ref: ./database/models/fieldType.openapi.yml
    Role:
      $ref: ./database/models/role.openapi.yml
    Status:
      $ref: ./database/models/status.openapi.yml
    Tag:
      $ref: ./database/models/tag.openapi.yml
    Template:
      $ref: ./database/models/template.openapi.yml
    Transaction:
      $ref: ./database/models/transaction.openapi.yml
    User:
      $ref: ./database/models/user.openapi.yml
#  parameters:

