openapi: 3.0.3
servers:
  - url: https://flexible-finance-server.herokuapp.com/api-v1
    description: Production server
  - url: http://localhost:5000/api-v1
    description: Local server
info:
  description: >-
    This is the server for Flexible Finance.
  version: 1.0.0
  title: OpenAPI Flexible Finance
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
#tags:
paths:
  /account:
    $ref: ./app/routes/account.openapi.yml#/AccountRequests
  /account/{AccountId}:
    $ref: ./app/routes/account.openapi.yml#/AccountIdRequests
  /accounts:
    $ref: ./app/routes/account.openapi.yml#/AccountsRequests
  /accountGroup:
    $ref: ./app/routes/accountGroup.openapi.yml#/AccountGroupRequests
  /accountGroup/{AccountGroupId}:
    $ref: ./app/routes/accountGroup.openapi.yml#/AccountGroupIdRequests
  /accountGroups:
    $ref: ./app/routes/accountGroup.openapi.yml#/AccountGroupsRequests
  /auth/signup:
    $ref: ./app/routes/auth.openapi.yml#/SignUp
  /auth/signin:
    $ref: ./app/routes/auth.openapi.yml#/SignIn
  /api-docs:
    get:
      security: []
      responses:
        200:
          description: Returns API documentation.
          content:
            text/html:
              schema:
                type: string
  /entity:
    $ref: ./app/routes/entity.openapi.yml#/EntityRequests
  /entity/{EntityId}:
    $ref: ./app/routes/entity.openapi.yml#/EntityIdRequests
  /entities:
    $ref: ./app/routes/entity.openapi.yml#/EntitiesRequests
  /field:
    $ref: ./app/routes/field.openapi.yml#/FieldRequests
  /field/{FieldId}:
    $ref: ./app/routes/field.openapi.yml#/FieldIdRequests
  /fields:
    $ref: ./app/routes/field.openapi.yml#/FieldsRequests
  /fieldDatum:
    $ref: ./app/routes/fieldDatum.openapi.yml#/FieldDatumRequests
  /fieldDatum/{FieldDatumId}:
    $ref: ./app/routes/fieldDatum.openapi.yml#/FieldDatumIdRequests
  /fieldData:
    $ref: ./app/routes/fieldDatum.openapi.yml#/FieldDataRequests
  /fieldType:
    $ref: ./app/routes/fieldType.openapi.yml#/FieldTypeRequests
  /fieldType/{FieldTypeId}:
    $ref: ./app/routes/fieldType.openapi.yml#/FieldTypeIdRequests
  /fieldTypes:
    $ref: ./app/routes/fieldType.openapi.yml#/FieldTypesRequests
  /role:
    $ref: ./app/routes/role.openapi.yml#/RoleRequests
  /role/{RoleId}:
    $ref: ./app/routes/role.openapi.yml#/RoleIdRequests
  /roles:
    $ref: ./app/routes/role.openapi.yml#/RolesRequests
  /status:
    $ref: ./app/routes/status.openapi.yml#/StatusRequests
  /status/{StatusId}:
    $ref: ./app/routes/status.openapi.yml#/StatusIdRequests
  /statuses:
    $ref: ./app/routes/status.openapi.yml#/StatusesRequests
  /tag:
    $ref: ./app/routes/tag.openapi.yml#/TagRequests
  /tag/{TagId}:
    $ref: ./app/routes/tag.openapi.yml#/TagIdRequests
  /tags:
    $ref: ./app/routes/tag.openapi.yml#/TagsRequests
  /test/all:
    $ref: ./app/routes/authTest.openapi.yml#/TestAll
  /test/user:
    $ref: ./app/routes/authTest.openapi.yml#/TestUser
  /test/admin:
    $ref: ./app/routes/authTest.openapi.yml#/TestAdmin
  /template:
    $ref: ./app/routes/template.openapi.yml#/TemplateRequests
  /template/{TemplateId}:
    $ref: ./app/routes/template.openapi.yml#/TemplateIdRequests
  /templates:
    $ref: ./app/routes/template.openapi.yml#/TemplatesRequests
  /transaction:
    $ref: ./app/routes/transaction.openapi.yml#/TransactionRequests
  /transaction/{TransactionId}:
    $ref: ./app/routes/transaction.openapi.yml#/TransactionIdRequests
  /transactions:
    $ref: ./app/routes/transaction.openapi.yml#/TransactionsRequests
  /type:
    $ref: ./app/routes/type.openapi.yml#/TypeRequests
  /type/{TypeId}:
    $ref: ./app/routes/type.openapi.yml#/TypeIdRequests
  /types:
    $ref: ./app/routes/type.openapi.yml#/TypesRequests
  /user:
    $ref: ./app/routes/user.openapi.yml#/UserRequests
  /user/{UserId}:
    $ref: ./app/routes/user.openapi.yml#/UserIdRequests
  /users:
    $ref: ./app/routes/user.openapi.yml#/UsersRequests
components:
  responses:
    Message:
      description: a simple response with just a message
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Message"
    Account:
      $ref: ./app/routes/account.openapi.yml#/AccountResponse
    Accounts:
      $ref: ./app/routes/account.openapi.yml#/AccountsResponse
    AccountGroup:
      $ref: ./app/routes/accountGroup.openapi.yml#/AccountGroupResponse
    AccountGroups:
      $ref: ./app/routes/accountGroup.openapi.yml#/AccountGroupsResponse
    Entity:
      $ref: ./app/routes/entity.openapi.yml#/EntityResponse
    Entities:
      $ref: ./app/routes/entity.openapi.yml#/EntitiesResponse
    Field:
      $ref: ./app/routes/field.openapi.yml#/FieldResponse
    Fields:
      $ref: ./app/routes/field.openapi.yml#/FieldsResponse
    FieldDatum:
      $ref: ./app/routes/fieldDatum.openapi.yml#/FieldDatumResponse
    FieldData:
      $ref: ./app/routes/fieldDatum.openapi.yml#/FieldDataResponse
    FieldType:
      $ref: ./app/routes/fieldType.openapi.yml#/FieldTypeResponse
    FieldTypes:
      $ref: ./app/routes/fieldType.openapi.yml#/FieldTypesResponse
    Role:
      $ref: ./app/routes/role.openapi.yml#/RoleResponse
    Roles:
      $ref: ./app/routes/role.openapi.yml#/RolesResponse
    Status:
      $ref: ./app/routes/status.openapi.yml#/StatusResponse
    Statuses:
      $ref: ./app/routes/status.openapi.yml#/StatusesResponse
    Tag:
      $ref: ./app/routes/tag.openapi.yml#/TagResponse
    Tags:
      $ref: ./app/routes/tag.openapi.yml#/TagsResponse
    Template:
      $ref: ./app/routes/template.openapi.yml#/TemplateResponse
    Templates:
      $ref: ./app/routes/template.openapi.yml#/TemplatesResponse
    Transaction:
      $ref: ./app/routes/transaction.openapi.yml#/TransactionResponse
    Transactions:
      $ref: ./app/routes/transaction.openapi.yml#/TransactionsResponse
    Type:
      $ref: ./app/routes/type.openapi.yml#/TypeResponse
    Types:
      $ref: ./app/routes/type.openapi.yml#/TypesResponse
    User:
      $ref: ./app/routes/user.openapi.yml#/UserResponse
    Users:
      $ref: ./app/routes/user.openapi.yml#/UsersResponse
  schemas:
    Message:
      type: object
      properties:
        message:
          type: string
    Account:
      $ref: ./database/models/account.openapi.yml
    AccountGroup:
      $ref: ./database/models/accountGroup.openapi.yml
    Entity:
      $ref: ./database/models/entity.openapi.yml
    Field:
      $ref: ./database/models/field.openapi.yml
    FieldDatum:
      $ref: ./database/models/fieldDatum.openapi.yml
    FieldType:
      $ref: ./database/models/fieldType.openapi.yml
    Role:
      $ref: ./database/models/role.openapi.yml
    Status:
      $ref: ./database/models/status.openapi.yml
    Tag:
      $ref: ./database/models/tag.openapi.yml
    Template:
      $ref: ./database/models/template.openapi.yml
    Transaction:
      $ref: ./database/models/transaction.openapi.yml
    Type:
      $ref: ./database/models/type.openapi.yml
    User:
      $ref: ./database/models/user.openapi.yml
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
#  parameters:
security:
  - bearerAuth: []
